FIND_PATH(CSAFESTRING_INCLUDE_DIR csafestring.h
        /usr/local/include
        /usr/include
        )

SET(CSAFESTRING_NAMES ${CSAFESTRING_NAMES} csafestring)
FIND_LIBRARY(CSAFESTRING_LIBRARY
        NAMES ${CSAFESTRING_NAMES}
        PATHS /usr/lib /usr/local/lib
        )

IF (CSAFESTRING_LIBRARY AND CSAFESTRING_INCLUDE_DIR)
    SET(CSAFESTRING_LIBRARIES ${CSAFESTRING_LIBRARY})
    SET(CSAFESTRING_FOUND "YES")
ELSE (CSAFESTRING_LIBRARY AND CSAFESTRING_INCLUDE_DIR)
    SET(CSAFESTRING_FOUND "NO")
ENDIF (CSAFESTRING_LIBRARY AND CSAFESTRING_INCLUDE_DIR)


IF (CSAFESTRING_FOUND)
    IF (NOT CSAFESTRING_FIND_QUIETLY)
        MESSAGE(STATUS "Found CSAFESTRING: ${CSAFESTRING_LIBRARIES}")
    ENDIF (NOT CSAFESTRING_FIND_QUIETLY)
ELSE (CSAFESTRING_FOUND)
    IF (CSAFESTRING_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find CSAFESTRING library")
    ENDIF (CSAFESTRING_FIND_REQUIRED)
ENDIF (CSAFESTRING_FOUND)
