FIND_PATH(JSON2MAP_INCLUDE_DIR json2map.h map2json.h
        /usr/local/include
        /usr/include
        )

SET(JSON2MAP_NAMES ${JSON2MAP_NAMES} json2map)
FIND_LIBRARY(JSON2MAP_LIBRARY
        NAMES ${JSON2MAP_NAMES}
        PATHS /usr/lib /usr/local/lib
        )

IF (JSON2MAP_LIBRARY AND JSON2MAP_INCLUDE_DIR)
    SET(JSON2MAP_LIBRARIES ${JSON2MAP_LIBRARY})
    SET(JSON2MAP_FOUND "YES")
ELSE (JSON2MAP_LIBRARY AND JSON2MAP_INCLUDE_DIR)
    SET(JSON2MAP_FOUND "NO")
ENDIF (JSON2MAP_LIBRARY AND JSON2MAP_INCLUDE_DIR)


IF (JSON2MAP_FOUND)
    IF (NOT JSON2MAP_FIND_QUIETLY)
        MESSAGE(STATUS "Found JSON2MAP: ${JSON2MAP_LIBRARIES}")
    ENDIF (NOT JSON2MAP_FIND_QUIETLY)
ELSE (JSON2MAP_FOUND)
    IF (JSON2MAP_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find JSON2MAP library")
    ENDIF (JSON2MAP_FIND_REQUIRED)
ENDIF (JSON2MAP_FOUND)
